### ISSUE TITLE
Implement teaming up email functionality

### ISSUE THREAD

**Issue by thaneesh-babu** [HackGT/match#18]
Implementing sending an email with a custom message when you ask to team up with a user, using a view like below

![image](https://github.com/HackGT/match/assets/63804742/8ffb78e4-d1bb-4631-b81a-f3a85ac38d25)

The API endpoint you should be using is [this](https://github.com/HackGT/api/blob/main/services/notifications/src/routes/email.ts#L36)

**Comment by reesewang25** [comment]
![image](https://github.com/HackGT/match/assets/65859329/971a967a-b70d-4f93-9c4b-af865c0946e3)
