### ISSUE TITLE
Add sorting/filtering for profile fields

### ISSUE THREAD

**Issue by amtang325** [HackGT/match#3]
- Filter by commitment level, skills, schools
- Create a common definitions file with skills and schools from [here](https://github.com/HackGT/api/blob/main/common/src/commonDefinitions.ts) and use that for filtering

**Comment by thaneesh-babu** [comment]
TODO: 
- create a definitions file for schools like how it was done for skills and support filtering for that as well
- a definitions file for commitment as well so that `Display.tsx` looks cleaner
